services:
  eventstore-db:
    image: postgres
    container_name: odin-eventstore
    restart: unless-stopped
    environment:
      POSTGRES_USER: odin_user_es
      POSTGRES_PASSWORD: es_password
      POSTGRES_DB: eventstore
    volumes:
      - eventstore_pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  eventstore_pgdata:
